# Lab 01 Exercises: NumPy Arrays

Here are 15 exercises to help you practice what you've learned about NumPy arrays:

Remember to check the data type (`dtype`) of the arrays you create and observe the difference between arrays created with different methods (e.g., `zeros()`, `ones()`, `arange()`, `linspace()`).

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before. 

Also don't be shy! Ask for help in the discord forum.

1. Create a 1D NumPy array containing the numbers 1 to 10.


In [1]:
import numpy as np

In [4]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a)

(10,)
1
10
int32
[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 2D NumPy array with 3 rows and 4 columns, filled with zeros.


In [5]:
b = np.zeros((3,4), dtype=int)
print(b)
print(b.dtype)
print(b.ndim)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
2


3. Create a 3D NumPy array with 2 sets of 3 rows and 4 columns, filled with ones.


In [6]:
b = np.ones((2,3,4), dtype=int)
print(b)
print(b.dtype)
print(b.ndim)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int32
3


4. Create a 2D NumPy array with 2 rows and 3 columns, filled with the value 7.5.


In [7]:
b = np.ones((2,3))*7.5
print(b)
print(b.size)
print(b.ndim)
print(b.dtype)


[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
6
2
float64


5. Create a 1D NumPy array containing the numbers from 0 to 99, with a step of 3.


In [8]:
c = np.linspace(0,99,34,dtype=int)
print(c)
print(c.ndim)
print(c.size)
print(c.dtype)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
1
34
int32


6. Create a 1D NumPy array containing 15 linearly spaced numbers between 1 and 10.


In [9]:
c = np.linspace(1,10,15)
print(c)
print(c.size)
print(c.ndim)
print(c.dtype)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
15
1
float64



7. Create a 2D NumPy array with 5 rows and 3 columns, filled with numbers from 1 to 15.


In [10]:
c = np.arange(1,16)
b = c.reshape(5,3)
print(b)
print(b.ndim)
print(b.size)
print(b.dtype)
print(f'\nDimensions: {b.ndim}')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
2
15
int32

Dimensions: 2



8. Create a 2D NumPy array with 4 rows and 4 columns, filled with random integers between 0 and 9.


In [11]:
b = np.random.randint(10, size=(4, 4))  # Two-dimensional array
print(b)
print(b.size)
print(b.ndim)
print(b.dtype)

[[9 2 0 4]
 [9 8 5 6]
 [0 2 7 9]
 [2 8 8 3]]
16
2
int32



9. Given the following Python list: `[1, 2, 3, 4, 5]`, create a 1D NumPy array.


In [12]:
a = np.array([1,2,3,4,5])
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

[1 2 3 4 5]
5
1
int32



10. Given the following Python list of lists: `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`, create a 2D NumPy array.


In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
d = [a,b,c]

e = np.array([a,b,c])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



11. Create a 2D NumPy array with 3 rows and 3 columns, filled with the value 0. Replace the central value with 1.


In [14]:
a = np.zeros((3,3))
a[1][1] = 1
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
9
2
float64



12. Create a 1D NumPy array containing 20 linearly spaced numbers between 0 and 1.


In [13]:
a = np.linspace(0,1,20)
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
20
1
float64



13. Create a 2D NumPy array with 5 rows and 5 columns, filled with numbers from 0 to 24.


In [ ]:
a = np.arange(0,25,1)
print(a)
b = a.reshape(5,5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



14. Create a 3D NumPy array with 2 sets of 2 rows and 3 columns, filled with the value 3.14.


In [15]:
a = np.ones((2,2,3))*3.14
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

[[[3.14 3.14 3.14]
  [3.14 3.14 3.14]]

 [[3.14 3.14 3.14]
  [3.14 3.14 3.14]]]
12
3
float64



15. Given the following Python list of tuples: `[(1, 2, 3), (4, 5, 6), (7, 8, 9)]`, create a 2D NumPy array.



In [18]:
a = (1,2,3)
b = (4,5,6)
c = (7,8,9)
d = [a,b,c]

e = np.array(d)
print(e)
print(e.size)
print(e.ndim)
print(e.dtype)
print(f'Dimension: {e.ndim}D')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
2
int32
Dimension: 2D
