
# NumPy Exercises for Operations

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

1. Create two 1D NumPy arrays with 5 elements each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.


In [74]:
import numpy as np

a = np.random.randint(1,10, size=5)
print(f'{a}      ->  a')

b = np.random.randint(1,10, size=5)
print(f'{b}      ->  b')


c = a + b
print(f'{c} ->  addition: a + b') 

f = a - b
print(f'{f} ->  subtraction: a - b') 

e = a * b
print(f'{e} ->  product: a * b')    

y = a / b
print(f'{y} ->  division: a / b')    


[3 3 5 1 6]      ->  a
[7 1 9 8 7]      ->  b
[10  4 14  9 13] ->  addition: a + b
[-4  2 -4 -7 -1] ->  subtraction: a - b
[21  3 45  8 42] ->  product: a * b
[0.42857143 3.         0.55555556 0.125      0.85714286] ->  division: a / b



2. Create a 2D NumPy array with 3 rows and 4 columns, filled with random floats between 0 and 1. Multiply each element in the array by 10 and then subtract 5 from each element.



2. Create a 2D NumPy array with 3 rows and 4 columns, filled with random floats between 0 and 1. Multiply each element in the array by 10 and then subtract 5 from each element.


In [ ]:
array_2 = np.random.uniform(0,1,size=12).reshape(3,4)
array_2_1 = array_2*10
array_2_2 = array_2_1-5
print(f'original array: \n{array_2}\n')
print(f'Multiply by 10: \n{array_2_1}\n')
print(f'Subtract 5: \n{array_2_2}\n')

original array: 
[[0.78808753 0.77784082 0.95412775 0.69747638]
 [0.6620612  0.03625177 0.16881103 0.07648641]
 [0.74634313 0.23459853 0.56518297 0.36201034]]

Multiply by 10: 
[[7.88087528 7.77840822 9.54127746 6.97476384]
 [6.62061201 0.36251765 1.68811029 0.76486408]
 [7.46343128 2.34598532 5.65182965 3.62010343]]

Subtract 5: 
[[ 2.88087528  2.77840822  4.54127746  1.97476384]
 [ 1.62061201 -4.63748235 -3.31188971 -4.23513592]
 [ 2.46343128 -2.65401468  0.65182965 -1.37989657]]




3. Create two 2D NumPy arrays with 2 rows and 3 columns each, filled with random integers between 1 and 5. Perform matrix multiplication on these arrays using the `@` operator.


In [114]:
a_2d = np.random.randint(1,5, size=(2,3))
b_2d = np.random.randint(1,5, size=(2,3))

print(f'a: \n{a_2d}')
print(f'b: \n{b_2d}')
print(f'a.T: \n{a_2d.T}')
print(f'b.T: \n{b_2d.T}')

c = a_2d @ b_2d.T
d = a_2d.T @ b_2d
print(f'Matrix multiplication a@b.T: \n{c}')
print(f'Matrix multiplication a.T@b: \n{d}')


a: 
[[3 1 3]
 [3 3 4]]
b: 
[[4 4 2]
 [2 2 1]]
a.T: 
[[3 3]
 [1 3]
 [3 4]]
b.T: 
[[4 2]
 [4 2]
 [2 1]]
Matrix multiplication a@b.T: 
[[22 11]
 [32 16]]
Matrix multiplication a.T@b: 
[[18 18  9]
 [10 10  5]
 [20 20 10]]



4. Create a 2D NumPy array with 4 rows and 4 columns, filled with random integers between 1 and 10. Calculate the sum, mean, and standard deviation of all elements in the array.


In [123]:
array_4 = np.random.randint(1,10, size=(4,4))
print(array_4)

sum = np.sum(array_4)
mean = np.mean(array_4)
stnd = np.std(array_4)
print(f'sum: {sum}')
print(f'mean: {mean}')
print(f'standard deviation: {stnd}')



[[9 2 2 9]
 [3 9 7 2]
 [3 3 7 7]
 [8 5 6 2]]
sum: 84
mean: 5.25
standard deviation: 2.704163456597992



5. Using the array from exercise 4, calculate the sum, mean, and standard deviation along each row and each column.


In [128]:
sum_rows = np.sum(array_4, axis=1)
print(f'sum along rows: {sum_rows}')

sum_colums = np.sum(array_4, axis=0)
print(f'sum along colums: {sum_colums}')

sum along rows: [22 21 20 21]
sum along colums: [23 19 22 20]



6. Create a 1D NumPy array with 10 elements, filled with random integers between 1 and 100. Apply the following universal functions to the array: square root, natural logarithm, and exponential.


In [134]:
array_6 = np.random.randint(1,100, size=10)
print(f'Original array: {array_6}\n')

sqr_root = np.sqrt(array_6)
print(f'Square root: {sqr_root}\n')

log_ = np.log(array_6)  
print(f'Natural log: {log_}\n')

exp_ = np.exp(array_6)
print(f'Exponential: {exp_}\n')

Original array: [77 91 50 53 36 38 60 85 90 11]

Square root: [8.77496439 9.53939201 7.07106781 7.28010989 6.         6.164414
 7.74596669 9.21954446 9.48683298 3.31662479]

Natural log: [4.34380542 4.51085951 3.91202301 3.97029191 3.58351894 3.63758616
 4.09434456 4.44265126 4.49980967 2.39789527]

Exponential: [2.75851345e+33 3.31740010e+39 5.18470553e+21 1.04137594e+23
 4.31123155e+15 3.18559318e+16 1.14200739e+26 8.22301271e+36
 1.22040329e+39 5.98741417e+04]




7. Create a 2D NumPy array with 3 rows and 3 columns, filled with random floats between -1 and 1. Apply the following universal functions to the array: absolute value, sine, and cosine.


In [136]:
array_7 = np.random.uniform(-1,1, size=(3,3))
print(array_7)
print(array_7.dtype)

[[-0.23954015  0.6952006  -0.97834558]
 [-0.7987995   0.31894897 -0.02005903]
 [ 0.3307896  -0.33692598 -0.64451656]]
float64



8. Create two 1D NumPy arrays with 6 elements each, filled with random integers between 1 and 10. Perform element-wise comparison operations on these arrays: greater than, less than, and equal to.


In [159]:
array_8_1 = np.random.randint(1,10, size=6)
array_8_2 = np.random.randint(1,10, size=6)
print(f'array 1: {array_8_1}')
print(f'array 2: {array_8_2}\n')

greater_1 = array_8_1[array_8_1>3]
greater_2 = array_8_2[array_8_2>3]
print(f'Greater than 3 in array 1: {greater_1}')
print(f'Greater than 3 in array 2: {greater_2}\n')

less_1 = array_8_1[array_8_1<3]
less_2 = array_8_2[array_8_2<3]
print(f'Less than 3 in array 1: {less_1}')
print(f'Less than 3 in array 2: {less_2}\n')

equal_1 = array_8_1[array_8_1==3]
equal_2 = array_8_2[array_8_2==3]
print(f'Equal to 3 in array 1: {equal_1}')
print(f'Equal to 3 in array 2: {equal_2}')

array 1: [3 3 9 3 2 3]
array 2: [7 2 5 8 8 9]

Greater than 3 in array 1: [9]
Greater than 3 in array 2: [7 5 8 8 9]

Less than 3 in array 1: [2]
Less than 3 in array 2: [2]

Equal to 3 in array 1: [3 3 3 3]
Equal to 3 in array 2: []



9. Create a 2D NumPy array with 5 rows and 5 columns, filled with random integers between 1 and 100. Find the maximum and minimum values in the array along each row and each column.



10. Create a 1D NumPy array with 8 elements, filled with random integers between 1 and 20. Calculate the dot product of this array with itself.



11. Create a 2D NumPy array with 4 rows and 4 columns, filled with random floats between 0 and 1. Apply the following universal functions to the array: ceil, floor, and round.



12. Create two 2D NumPy arrays with 3 rows and 3 columns each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.



13. Create a 1D NumPy array with 7 elements, filled with random integers between 1 and 100. Calculate the sum of the array using a Python loop and compare the execution time with the NumPy `sum()` function using the `%%timeit` magic command.



14. Create a 2D NumPy array with 6 rows and 6 columns, filled with random floats between -10 and 10. Apply the following universal functions to the array: hyperbolic sine, hyperbolic cosine, and hyperbolic tangent. (Practice those look up skills!)



15. Create two 1D NumPy arrays with 100 elements each, filled with random floats between 0 and 1. Perform element-wise multiplication on these arrays using a Python loop and compare the execution time with the NumPy element-wise multiplication using the `%%timeit` magic command.