
# NumPy Exercises for Operations

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

1. Create two 1D NumPy arrays with 5 elements each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.


In [74]:
import numpy as np

a = np.random.randint(1,10, size=5)
print(f'{a}      ->  a')

b = np.random.randint(1,10, size=5)
print(f'{b}      ->  b')


c = a + b
print(f'{c} ->  addition: a + b') 

f = a - b
print(f'{f} ->  subtraction: a - b') 

e = a * b
print(f'{e} ->  product: a * b')    

y = a / b
print(f'{y} ->  division: a / b')    


[3 3 5 1 6]      ->  a
[7 1 9 8 7]      ->  b
[10  4 14  9 13] ->  addition: a + b
[-4  2 -4 -7 -1] ->  subtraction: a - b
[21  3 45  8 42] ->  product: a * b
[0.42857143 3.         0.55555556 0.125      0.85714286] ->  division: a / b



2. Create a 2D NumPy array with 3 rows and 4 columns, filled with random floats between 0 and 1. Multiply each element in the array by 10 and then subtract 5 from each element.



2. Create a 2D NumPy array with 3 rows and 4 columns, filled with random floats between 0 and 1. Multiply each element in the array by 10 and then subtract 5 from each element.


In [ ]:
array_2 = np.random.uniform(0,1,size=12).reshape(3,4)
array_2_1 = array_2*10
array_2_2 = array_2_1-5
print(f'original array: \n{array_2}\n')
print(f'Multiply by 10: \n{array_2_1}\n')
print(f'Subtract 5: \n{array_2_2}\n')

original array: 
[[0.78808753 0.77784082 0.95412775 0.69747638]
 [0.6620612  0.03625177 0.16881103 0.07648641]
 [0.74634313 0.23459853 0.56518297 0.36201034]]

Multiply by 10: 
[[7.88087528 7.77840822 9.54127746 6.97476384]
 [6.62061201 0.36251765 1.68811029 0.76486408]
 [7.46343128 2.34598532 5.65182965 3.62010343]]

Subtract 5: 
[[ 2.88087528  2.77840822  4.54127746  1.97476384]
 [ 1.62061201 -4.63748235 -3.31188971 -4.23513592]
 [ 2.46343128 -2.65401468  0.65182965 -1.37989657]]




3. Create two 2D NumPy arrays with 2 rows and 3 columns each, filled with random integers between 1 and 5. Perform matrix multiplication on these arrays using the `@` operator.


In [114]:
a_2d = np.random.randint(1,5, size=(2,3))
b_2d = np.random.randint(1,5, size=(2,3))

print(f'a: \n{a_2d}')
print(f'b: \n{b_2d}')
print(f'a.T: \n{a_2d.T}')
print(f'b.T: \n{b_2d.T}')

c = a_2d @ b_2d.T
d = a_2d.T @ b_2d
print(f'Matrix multiplication a@b.T: \n{c}')
print(f'Matrix multiplication a.T@b: \n{d}')


a: 
[[3 1 3]
 [3 3 4]]
b: 
[[4 4 2]
 [2 2 1]]
a.T: 
[[3 3]
 [1 3]
 [3 4]]
b.T: 
[[4 2]
 [4 2]
 [2 1]]
Matrix multiplication a@b.T: 
[[22 11]
 [32 16]]
Matrix multiplication a.T@b: 
[[18 18  9]
 [10 10  5]
 [20 20 10]]



4. Create a 2D NumPy array with 4 rows and 4 columns, filled with random integers between 1 and 10. Calculate the sum, mean, and standard deviation of all elements in the array.


In [123]:
array_4 = np.random.randint(1,10, size=(4,4))
print(array_4)

sum = np.sum(array_4)
mean = np.mean(array_4)
stnd = np.std(array_4)
print(f'sum: {sum}')
print(f'mean: {mean}')
print(f'standard deviation: {stnd}')



[[9 2 2 9]
 [3 9 7 2]
 [3 3 7 7]
 [8 5 6 2]]
sum: 84
mean: 5.25
standard deviation: 2.704163456597992



5. Using the array from exercise 4, calculate the sum, mean, and standard deviation along each row and each column.


In [128]:
sum_rows = np.sum(array_4, axis=1)
print(f'sum along rows: {sum_rows}')

sum_colums = np.sum(array_4, axis=0)
print(f'sum along colums: {sum_colums}')

sum along rows: [22 21 20 21]
sum along colums: [23 19 22 20]



6. Create a 1D NumPy array with 10 elements, filled with random integers between 1 and 100. Apply the following universal functions to the array: square root, natural logarithm, and exponential.


In [134]:
array_6 = np.random.randint(1,100, size=10)
print(f'Original array: {array_6}\n')

sqr_root = np.sqrt(array_6)
print(f'Square root: {sqr_root}\n')

log_ = np.log(array_6)  
print(f'Natural log: {log_}\n')

exp_ = np.exp(array_6)
print(f'Exponential: {exp_}\n')

Original array: [77 91 50 53 36 38 60 85 90 11]

Square root: [8.77496439 9.53939201 7.07106781 7.28010989 6.         6.164414
 7.74596669 9.21954446 9.48683298 3.31662479]

Natural log: [4.34380542 4.51085951 3.91202301 3.97029191 3.58351894 3.63758616
 4.09434456 4.44265126 4.49980967 2.39789527]

Exponential: [2.75851345e+33 3.31740010e+39 5.18470553e+21 1.04137594e+23
 4.31123155e+15 3.18559318e+16 1.14200739e+26 8.22301271e+36
 1.22040329e+39 5.98741417e+04]




7. Create a 2D NumPy array with 3 rows and 3 columns, filled with random floats between -1 and 1. Apply the following universal functions to the array: absolute value, sine, and cosine.


In [136]:
array_7 = np.random.uniform(-1,1, size=(3,3))
print(array_7)
print(array_7.dtype)

[[-0.23954015  0.6952006  -0.97834558]
 [-0.7987995   0.31894897 -0.02005903]
 [ 0.3307896  -0.33692598 -0.64451656]]
float64



8. Create two 1D NumPy arrays with 6 elements each, filled with random integers between 1 and 10. Perform element-wise comparison operations on these arrays: greater than, less than, and equal to.


In [159]:
array_8_1 = np.random.randint(1,10, size=6)
array_8_2 = np.random.randint(1,10, size=6)
print(f'array 1: {array_8_1}')
print(f'array 2: {array_8_2}\n')

greater_1 = array_8_1[array_8_1>3]
greater_2 = array_8_2[array_8_2>3]
print(f'Greater than 3 in array 1: {greater_1}')
print(f'Greater than 3 in array 2: {greater_2}\n')

less_1 = array_8_1[array_8_1<3]
less_2 = array_8_2[array_8_2<3]
print(f'Less than 3 in array 1: {less_1}')
print(f'Less than 3 in array 2: {less_2}\n')

equal_1 = array_8_1[array_8_1==3]
equal_2 = array_8_2[array_8_2==3]
print(f'Equal to 3 in array 1: {equal_1}')
print(f'Equal to 3 in array 2: {equal_2}')

array 1: [3 3 9 3 2 3]
array 2: [7 2 5 8 8 9]

Greater than 3 in array 1: [9]
Greater than 3 in array 2: [7 5 8 8 9]

Less than 3 in array 1: [2]
Less than 3 in array 2: [2]

Equal to 3 in array 1: [3 3 3 3]
Equal to 3 in array 2: []



9. Create a 2D NumPy array with 5 rows and 5 columns, filled with random integers between 1 and 100. Find the maximum and minimum values in the array along each row and each column.


In [173]:
array_9_1 = np.random.randint(1,100, size=(5,5))

print(f"Array 1:\n{array_9_1}\n")

maximun_rows = np.max(array_9_1,axis=1)
print(f'max in each row: {maximun_rows}')

maximun_colums = np.max(array_9_1,axis=0)
print(f'max in each colum: {maximun_colums}')

minimum_rows = np.min(array_9_1, axis=1)
print(f'min in each row: {minimum_rows}')

minimun_colums = np.min(array_9_1,axis=0)
print(f'min in each colum: {minimun_colums}')

Array 1:
[[13 35 56 37 21]
 [68 51 18 54 16]
 [61 89 80 91 66]
 [95 96 62 94 77]
 [36 17 19 34  2]]

max in each row: [56 68 91 96 36]
max in each colum: [95 96 80 94 77]
min in each row: [13 16 61 62  2]
min in each colum: [13 17 18 34  2]



10. Create a 1D NumPy array with 8 elements, filled with random integers between 1 and 20. Calculate the dot product of this array with itself.


In [205]:
array_11 = np.random.randint(1,20, size=8)
print(array_11)
dot_ = np.dot(array_11, array_11)
print(dot_)

[19  9  7  9 11 18  5  9]
1123



11. Create a 2D NumPy array with 4 rows and 4 columns, filled with random floats between 0 and 1. Apply the following universal functions to the array: ceil, floor, and round.


In [210]:
array_11 = np.random.uniform(0,1,size=(4,4))
print(f'array:\n{array_11}\n')
ceil_ = np.ceil(array_11)
print(f'ceil:\n{ceil_}\n' )

floor_ = np.floor(array_11)
print(f'floor:\n{floor_}\n' )

round_ = np.round(array_11)
print(f'round:\n{round_}')

array:
[[0.53224948 0.33848533 0.01702459 0.59528498]
 [0.44275392 0.46409216 0.44086453 0.85270349]
 [0.24428839 0.57443699 0.34832645 0.8312474 ]
 [0.27513657 0.91536938 0.90956746 0.45484024]]

ceil:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

floor:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

round:
[[1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]



12. Create two 2D NumPy arrays with 3 rows and 3 columns each, filled with random integers between 1 and 10. Perform element-wise addition, subtraction, multiplication, and division on these arrays.


In [222]:
array_12_1 = np.random.randint(1,10, size=(3,3))
array_12_2 = np.random.randint(1,10, size=(3,3))
print(f"array 1:\n{array_12_1}\n")
print(f"array 2:\n{array_12_2}\n")

adition = array_12_1 + array_12_2
print(f'Addition array 1 + array 2:\n{adition}\n')

subtraction = array_12_1 - array_12_2 
print(f'subtraction array 1 - array 2:\n{subtraction}\n')

multiplication = array_12_1 * array_12_2
print(f'multiplication array 1 * array 2:\n{multiplication}\n')

division = array_12_1 / array_12_2
print(f'division array 1 / array 2:\n{division}\n')

array 1:
[[2 2 1]
 [1 4 1]
 [9 1 9]]

array 2:
[[7 5 9]
 [2 8 5]
 [8 4 5]]

Addition array 1 + array 2:
[[ 9  7 10]
 [ 3 12  6]
 [17  5 14]]

subtraction array 1 - array 2:
[[-5 -3 -8]
 [-1 -4 -4]
 [ 1 -3  4]]

multiplication array 1 * array 2:
[[14 10  9]
 [ 2 32  5]
 [72  4 45]]

division array 1 / array 2:
[[0.28571429 0.4        0.11111111]
 [0.5        0.5        0.2       ]
 [1.125      0.25       1.8       ]]




13. Create a 1D NumPy array with 7 elements, filled with random integers between 1 and 100. Calculate the sum of the array using a Python loop and compare the execution time with the NumPy `sum()` function using the `%%timeit` magic command.


In [287]:
%%time
array_13 = np.random.randint(1,100, size=7)
print(array_13)

sum = 0
for i in array_13:
    sum = sum + i
print(f'Sum of elements in array: {sum}')   

[19 84 95 24 23 61 13]
Sum of elements in array: 319
Wall time: 0 ns


In [286]:
%%time
array_13 = np.random.randint(1,100, size=7)
print(array_13)

sum_ = np.sum(array_13)
print(f'Sum of elements in array: {sum_}')   


[84 98 17 59  1 24 24]
Sum of elements in array: 307
Wall time: 996 µs



14. Create a 2D NumPy array with 6 rows and 6 columns, filled with random floats between -10 and 10. Apply the following universal functions to the array: hyperbolic sine, hyperbolic cosine, and hyperbolic tangent. (Practice those look up skills!)


In [294]:
array_14 = np.random.uniform(-10,10, size=(6,6))
print(array_14)

cosh_ = np.cosh(array_14)
sinh_ = np.sinh(array_14)
tanh_ = np.tanh(array_14)
print(cosh_)
print(sinh_)
print(tanh_)

[[ 0.15503901  6.01875738 -9.97024445  6.69198248 -6.5925969  -3.3877225 ]
 [-2.35990025  8.99124622  5.47204716 -7.34176466 -2.98643223 -7.4407103 ]
 [ 4.0964135   5.08001971 -7.56715953 -4.8606774   9.35060158 -7.41639267]
 [ 4.37364677 -2.60578468  8.12039594 -4.76959583  3.26912001  6.09518153]
 [-5.48203468  7.61088394  1.78301462 -2.04385175  4.24656086 -0.01334477]
 [ 9.33703875  2.1610669   5.68133726 -9.75385558 -8.4327021   1.03147885]]
[[1.01204264e+00 2.05534955e+02 1.06903556e+04 4.02959812e+02
  3.64837335e+02 1.48161252e+01]
 [5.34216236e+00 4.01623052e+03 1.18975506e+02 7.71716994e+02
  9.93266431e+00 8.51980348e+02]
 [3.00704485e+01 8.03917221e+01 9.66820277e+02 6.45596887e+01
  5.75287152e+03 8.31512101e+02]
 [3.96725086e+01 6.80784613e+00 1.68117603e+03 5.89400380e+01
  1.31631178e+01 2.21858419e+02]
 [1.20169688e+02 1.01003171e+03 3.05794509e+00 3.92490873e+00
  3.49395187e+01 1.00008904e+00]
 [5.67537306e+03 4.39779801e+00 1.46672425e+02 8.61024803e+03
  2.29744972


15. Create two 1D NumPy arrays with 100 elements each, filled with random floats between 0 and 1. Perform element-wise multiplication on these arrays using a Python loop and compare the execution time with the NumPy element-wise multiplication using the `%%timeit` magic command.

In [ ]:
%%time
array_15_1 = np.random.uniform(0,1, size=100000) # made it to 100k element to see the difference in %%time
array_15_2 = np.random.uniform(0,1, size=100000)

elem_mult = (array_15_1 * array_15_2)
print(elem_mult)


[0.11935679 0.26200167 0.29992915 ... 0.08924967 0.28077786 0.06394613]
Wall time: 6.02 ms


In [ ]:
%%time
array_15_1 = np.random.uniform(0,1, size=100000) # made it to 100k element to see the difference in %%time
array_15_2 = np.random.uniform(0,1, size=100000)

result_loop = []
for i in range(len(array_15_1)):
    result_loop.append(array_15_1[i] * array_15_2[i])

result_array = np.array(result_loop)
print(result_array)

[0.58995696 0.12480885 0.37750536 ... 0.24069885 0.26389501 0.21648547]
Wall time: 58.6 ms
