# 07 Views and Copies in Numpy Exercises

**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

You don't need to do all these (it's a lot!). As soon as you get the gist, feel free to move on.

1. Create a 1D NumPy array with 10 elements. Create a view of the first 5 elements and modify the 3rd element of the view. Check if the original array has been modified.


In [2]:
import numpy as np

a = np.arange(10)
print(f'Array: {a}')

a_view = a[:5]
a_view[2] = 99
print(f'view of 5 first elements: {a_view}')
print(f'Base of view: {a_view.base}')

Array: [0 1 2 3 4 5 6 7 8 9]
view of 5 first elements: [ 0  1 99  3  4]
Base of view: [ 0  1 99  3  4  5  6  7  8  9]



2. Create a 1D NumPy array with 10 elements. Create a copy of the first 5 elements and modify the 3rd element of the copy. Check if the original array has been modified.


In [27]:
a = np.arange(10)
print(f'Original array: {a}')
b = a[:5].copy()
b[2] = 0
print(f'Copy array: {b}')
print(f'Original array: {a}')


Original array: [0 1 2 3 4 5 6 7 8 9]
Copy array: [0 1 0 3 4]
Original array: [0 1 2 3 4 5 6 7 8 9]



3. Create a 2D NumPy array with 4 rows and 5 columns. Create a view of the first 2 rows and modify the element at (1, 1). Check if the original array has been modified.


In [49]:
a = np.arange(3,23).reshape(4, 5)
print(f'2D NumPy original array:\n{a}\n')
view_a = a[:2]
print(f'View of the first 2 rows:\n{view_a}\n')
view_a[1,1] = 0
print(f'View with 1,1 modified:\n{view_a}\n')
print(f'View base:\n{view_a.base}\n ')
print(f'2D NumPy original array modified:\n{a}\n')



2D NumPy original array:
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]

View of the first 2 rows:
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]

View with 1,1 modified:
[[ 3  4  5  6  7]
 [ 8  0 10 11 12]]

View base:
[ 3  4  5  6  7  8  0 10 11 12 13 14 15 16 17 18 19 20 21 22]
 
2D NumPy original array modified:
[[ 3  4  5  6  7]
 [ 8  0 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]




4. Create a 2D NumPy array with 4 rows and 5 columns. Create a copy of the first 2 rows and modify the element at (1, 1). Check if the original array has been modified.


In [52]:
array = np.arange(20).reshape(4,5)  
print(f'Array:\n{array}\n')
copy = array[:2].copy()
copy[1,1] = 0
print(f'Copy modified:\n{copy}\n')
print(f'Copy Base: {copy.base}\n')

Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Copy modified:
[[0 1 2 3 4]
 [5 0 7 8 9]]

Copy Base: None




5. Create a 1D NumPy array with 10 elements. Create a variable using boolean indexing (e.g., `arr[arr > 5]`) and modify the first element of the variable. Check if the original array has been modified.


In [ ]:
a = np.arange(10)
print(a)
view = a[a>5]
print(view)
view[0] = 99
print(view)
print(view.base)
print(a)
print("Seems like the ogirinal array has not been modified.")

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[99  7  8  9]
None
[0 1 2 3 4 5 6 7 8 9]
Seems like the ogirinal array has not been modified.



6. Create a 1D NumPy array with 10 elements. Create a variable using boolean indexing with `copy()` (e.g., `arr[arr > 5].copy()`) and modify the first element of the variable. Check if the original array has been modified.


In [63]:
a = np.arange(10)
print(a)
view = a[a>5].copy()
print(view)
view[0] = 99
print(view)
print(view.base)
print(a)
print("Seems like the ogirinal array has not been modified.")

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[99  7  8  9]
None
[0 1 2 3 4 5 6 7 8 9]
Seems like the ogirinal array has not been modified.



7. Create a 2D NumPy array with 5 rows and 5 columns. Create a variable using integer array indexing (e.g., `arr[[1, 2], [3, 4]]`) and modify the first element of the variable. Check if the original array has been modified.


In [83]:
a = np.arange(25).reshape(5,5)
print(f'Original array:\n{a}\n')
varr = a[[4,3],[2,3]]
print(f'variable array:\n{varr}\n')
varr[0] = 0
print(f'varr: {varr}')
print(f'varr base: {varr.base}\n')
print(f'Original array was not modified:\n{a}\n')


Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

variable array:
[22 18]

varr: [ 0 18]
varr base: None

Original array was not modified:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]




8. Create a 2D NumPy array with 5 rows and 5 columns. Create a variable using integer array indexing (e.g., `arr[[1, 2], [3, 4]].copy()`) and modify the first element of the variable. Check if the original array has been modified.


In [86]:
a = np.arange(25).reshape(5,5)
print(f'Original array:\n{a}\n')
view = a[[1,2], [3,4]].copy()
varr[0] = 0
print(f'varr: {varr}')
print(f'varr base: {varr.base}\n')
print(f'Original array was not modified:\n{a}\n')

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

varr: [ 0 18]
varr base: None

Original array was not modified:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]




9. Create a 1D NumPy array with 12 elements. Reshape the array into a 3x4 matrix. Create a view of the first row and modify the 2nd element of the view. Check if the original array has been modified.


In [100]:
a = np.arange(12).reshape(3,4)
print(f'Array:\n{a}\n')
view = a[0,:]
print(f'View of the first row:\n{view}\n')
view[1]= 0
print(f'View modified:\n{view}\n')
print(f'Original array was modified:\n{a}\n')
print(f'Shape of view: {view.shape}\n')


Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

View of the first row:
[0 1 2 3]

View modified:
[0 0 2 3]

Original array was modified:
[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape of view: (4,)




10. Create a 1D NumPy array with 12 elements. Reshape the array into a 3x4 matrix. Create a copy of the first row using `arr[0].copy()` and modify the 2nd element of the copy. Check if the original array has been modified.


In [101]:
a = np.arange(12).reshape(3,4)
print(f'Array:\n{a}\n')
view = a[0,:].copy()
print(f'View of the first row:\n{view}\n')
view[1]= 0
print(f'View modified:\n{view}\n')
print(f'Original array was not modified:\n{a}\n')
print(f'Shape of view: {view.shape}\n')


Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

View of the first row:
[0 1 2 3]

View modified:
[0 0 2 3]

Original array was not modified:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape of view: (4,)




11. Create a 2D NumPy array with 6 rows and 6 columns. Create a view of every other row starting from the first row and modify the element at (1, 1). Check if the original array has been modified.


In [103]:
a = np.arange(7,43).reshape(6,6)
print(f'Array:\n{a}\n')

view = a[2:,:]
view[1,1]=0

print(f'View: {view}\n')
print(f'View base: {view.base}\n')
print(f'Original array was modified:\n{a}')

Array:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]]

View: [[19 20 21 22 23 24]
 [25  0 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]]

View base: [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25  0 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42]

Original array was modified:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25  0 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]]



12. Create a 2D NumPy array with 6 rows and 6 columns. Create a copy of every other row starting from the first row and modify the element at (1, 1). Check if the original array has been modified.


In [107]:
a = np.arange(101,137).reshape(6,6)
print(f'Array:\n{a}\n')

b = a[2:,:].copy()
b[1,1]=0
print(f'Origina array was not modified:\n{a}')

Array:
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]
 [125 126 127 128 129 130]
 [131 132 133 134 135 136]]

Origina array was not modified:
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]
 [125 126 127 128 129 130]
 [131 132 133 134 135 136]]



13. Create a 2D NumPy array with 4 rows and 5 columns. Use boolean indexing to create a view of the elements greater than 10 and modify the first element of the view. Check if the original array has been modified.



14. Create a 2D NumPy array with 4 rows and 5 columns. Use boolean indexing to create a copy of the elements greater than 10 and modify the first element of the copy. Check if the original array has been modified.


In [11]:
array = np.arange(1,21).reshape(4,5)
mask = array > 10
view = array[mask]
view[0] = 0
print(f'Array:\n{array}\n')
print(f'View:\n{view.reshape(2,-1)}\n')

print(f'Array was not modified:\n{array}\n')
print(f'Base View: {view.base}\n')

Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

View:
[[ 0 12 13 14 15]
 [16 17 18 19 20]]

Array was not modified:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Base View: None




15. Create a 1D NumPy array with 15 elements. Create a view of the array using slicing and assign it to a new variable. Modify the first element of the view and check if the `.base` attribute of the view points to the original array.

In [142]:
a = np.arange(1,15)
slice_view = a[2:10]
slice_view[0] = 0
print(f'Array: {a}\n')
print(f'Slice view: {slice_view}\n')
print(f'Slice view base attribute points to the original array, and it was modified: {slice_view.base}\n')

Array: [ 1  2  0  4  5  6  7  8  9 10 11 12 13 14]

Slice view: [ 0  4  5  6  7  8  9 10]

Slice view base attribute points to the original array, and it was modified: [ 1  2  0  4  5  6  7  8  9 10 11 12 13 14]

