# 08 Exercises: Manipulating Arrays in NumPy
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!


1. Create a 1D NumPy array with 12 elements and reshape it into a 3x4 matrix.


In [2]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(f'Array:\n{a}\n')

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]




2. Create a 1D NumPy array with 20 elements and reshape it into a 4x5 matrix.


In [12]:
a = np.arange(20)
b = a.reshape(4,5)
print(f'Array a: {a}\n')
print(f'Reshape b:\n{b}\n')
print(f'Base b: {b.base}\n')

Array a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshape b:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Base b: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]




3. Create a 1D NumPy array with 30 elements and reshape it into a 3D array with dimensions 2x3x5.


In [13]:
a = np.arange(30).reshape(2,3,5)
print(f'Array:\n{a}\n')


Array:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]




4. Create a 2D NumPy array with dimensions 4x6 and flatten it into a 1D array using `flatten()`.


In [27]:
a = np.arange(24).reshape(4,-1)
print(f'Array:\n{a}\n')
a = a.flatten()
print(f'Array flattened:\n{a}\n')


Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Array flattened:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]




5. Create a 2D NumPy array with dimensions 5x5 and flatten it into a 1D array using `ravel()`.


In [29]:
a = np.arange(25).reshape(5,5)
print(f'Array:\n{a}\n')
a = a.ravel()
print(f'Array 1D using ravel():\n{a}\n')

Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array 1D using ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]




6. Create a 3D NumPy array with dimensions 2x3x4 and flatten it into a 1D array using `reshape(-1)`.


In [32]:
a = np.arange(24).reshape(2,3,4)
print(f'Array:\n{a}')

a=a.reshape(-1)
print(f'Array reshaped:\n{a}')

Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array reshaped:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]



7. Create a 1D NumPy array with 10 elements and add a new axis to create a column vector using `np.newaxis`.


In [39]:
a = np.arange(10)
print(f'array: {a}\n')
a = a[:,np.newaxis]
print(f'array: {a}\n')


array: [0 1 2 3 4 5 6 7 8 9]

array: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]




8. Create a 1D NumPy array with 10 elements and add a new axis to create a row vector using `np.expand_dims`.


In [46]:
a = np.arange(10)
print(f'Array: {a}\n')
row_vector = np.expand_dims(a, axis=0)
print(f'Array row vector: {row_vector}\n')


Array: [0 1 2 3 4 5 6 7 8 9]

Array row vector: [[0 1 2 3 4 5 6 7 8 9]]




9. Create a 2D NumPy array with dimensions 3x4 and add a new axis to create a 3D array with dimensions 1x3x4 using `np.newaxis`.


In [54]:
a = np.arange(12).reshape(3,4)
print(f'Array:\n{a}\n')
print(f'Array shape:\n{a.shape}\n')

b = a[np.newaxis]
print(f'Array with new dimension:\n{b}\n')

print(f'Shape of expanded array: {b.shape}\n')

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array shape:
(3, 4)

Array with new dimension:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

Shape of expanded array: (1, 3, 4)




10. Create two 1D NumPy arrays with 5 elements each and stack them vertically using `np.vstack()`.


In [ ]:
a = np.arange(5)
b = np.arange(5,10)
c = np.vstack((a,b))
print(f'stacked array v:\n{c}\n')

stacked array:
[[0 1 2 3 4]
 [5 6 7 8 9]]




11. Create two 1D NumPy arrays with 5 elements each and stack them horizontally using `np.hstack()`.


In [57]:
a = np.arange(5)
b = np.arange(5,10)
c = np.hstack((a,b))
print(f'stacked array h:\n{c}\n')

stacked array h:
[0 1 2 3 4 5 6 7 8 9]




12. Create two 2D NumPy arrays with dimensions 2x3 and concatenate them vertically using `np.concatenate()`.


In [63]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
c = np.concatenate((a,b),axis=0)
print(f'Concatenate array vectically:\n{c}\n  ')

Concatenate array vectically:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
  



13. Create two 2D NumPy arrays with dimensions 2x3 and concatenate them horizontally using `np.concatenate()`.


In [64]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
c = np.concatenate((a,b),axis=1)
print(f'Concatenate array horizontally:\n{c}\n  ')

Concatenate array horizontally:
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
  



14. Create a 3D NumPy array with dimensions 2x3x4 and remove all the single-dimensional entries using `np.squeeze()`.


In [ ]:
a = np.arange(24).reshape(2,3,4)
b = np.squeeze(a)
print(f'Array:\n{a}\n')
print(f'Array  shape: {a.shape}\n')
print(f'Array squezed:\n{b}\n')
print(f'Array squezed shape: {b.shape}\n')
# seems like there are not 1 size dimensions to remove

Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Array  shape: (2, 3, 4)

Array squezed:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Array squezed shape: (2, 3, 4)




15. Create a 2D NumPy array with dimensions 4x4 and reshape it into a 1D array. Then, add two new axes to create a 16x1x1 array using `np.expand_dims()`.

In [ ]:
a = np.arange(16).reshape(4,4)
b = a.reshape(-1)
e = np.expand_dims(b, axis=(1,-1))
print(e)
print(e.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]]
(16, 1, 1)
