# 09 Exercises: Sorting
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

Remember to print the original array and the sorted array (or indices) for each exercise to check your results.


1. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in ascending order using `np.sort()`.


In [2]:
import numpy as np

a = np.random.randint(0,100,size=10)
b = np.sort(a)
print(a)
print(b)

[19 53 17 92 89 52 71 74 13 81]
[13 17 19 52 53 71 74 81 89 92]



2. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in descending order using `np.sort()` and the `[::-1]` slicing technique.


In [13]:
a = np.random.randint(0,100, size=10)
b = np.sort(a)[::-1]
print(a)
print(b)

[43 41 22 64  9 93 74  9 11 48]
[93 74 64 48 43 41 22 11  9  9]



3. Create a 1D NumPy array with 10 random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array in ascending order.


In [16]:
a = np.random.randint(1,100, size=10)
indices_ = np.argsort(a)
indices_sorted = np.sort(indices_)
print(a)
print(indices_)
print(indices_sorted)


[ 5 96 38 57 95 87 73 12 64 27]
[0 7 9 2 3 8 6 5 4 1]
[0 1 2 3 4 5 6 7 8 9]



4. Create a 1D NumPy array with 10 random integers between 1 and 100. Sort the array in-place using the `sort()` method.


In [3]:
a = np.random.randint(1,100,size=10)
a.sort()
print(a)

[14 43 48 64 78 87 97 98 99 99]



5. Create a 2D NumPy array with dimensions 3x4 filled with random integers between 1 and 100. Sort the array along the first axis (rows) using `np.sort()`.


In [ ]:
a = np.random.randint(1,100,size=(3,4))
b = np.sort(a, axis=0)
print(f'original array:\n{a}\n')
print(f'sorted array down the colums:\n{b}')


original array:
[[48 22 83 42]
 [64 65 93 78]
 [51 18 16 83]]

sorted array along rows:
[[48 18 16 42]
 [51 22 83 78]
 [64 65 93 83]]



6. Create a 2D NumPy array with dimensions 4x5 filled with random integers between 1 and 100. Sort the array along the second axis (columns) using `np.sort()`.


In [26]:
a = np.random.randint(1,100,size=(4,5))
print(f'Array:\n{a}\n')
sorted_array = np.sort(a, axis=1)
print(f'Sorted array across the rows:\n{sorted_array}\n')

Array:
[[70 53 97 20 76]
 [97 81 21 19 46]
 [23 51 61 31 91]
 [13 77 22 19 98]]

Sorted array across the rows:
[[20 53 70 76 97]
 [19 21 46 81 97]
 [23 31 51 61 91]
 [13 19 22 77 98]]




7. Create a 2D NumPy array with dimensions 5x5 filled with random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array along the first axis (rows).


In [41]:
a = np.random.randint(1,100,size=(5,5))
print(f'Array:\n{a}\n')
indices_ = np.argsort(a, axis=0)
print(f'Indices array sorted across rows/along colums:\n{indices_}\n')

a.sort(axis=0)
print(f'Sorted array across rows/along colums:\n{a}')

Array:
[[79 75 59 48 83]
 [39 46 23 34 37]
 [18 66 29 58 66]
 [87 87 49 49 46]
 [93 33 33 23  1]]

Indices array sorted across rows/along colums:
[[2 4 1 4 4]
 [1 1 2 1 1]
 [0 2 4 0 3]
 [3 0 3 3 2]
 [4 3 0 2 0]]

Sorted array across rows/along colums:
[[18 33 23 23  1]
 [39 46 29 34 37]
 [79 66 33 48 46]
 [87 75 49 49 66]
 [93 87 59 58 83]]



8. Create a 2D NumPy array with dimensions 4x6 filled with random integers between 1 and 100. Use `np.argsort()` to get the indices that would sort the array along the second axis (columns).


In [45]:
array = np.random.randint(1,100,size=(4,6))
print(f'Array:\n{array}\n')

sorted_array = np.argsort(array, axis=1)
print(f'Indices array sorted across colums/along rows:\n{sorted_array}\n')

array.sort(axis=1)
print(f'Sorted array across columns/along rows:\n{array}')

Array:
[[43 26 68 42 99 91]
 [45 76 67 42 60 94]
 [38 14 32 42 43 41]
 [29 81 79 63 14 13]]

Indices array sorted across colums/along rows:
[[1 3 0 2 5 4]
 [3 0 4 2 1 5]
 [1 2 0 5 3 4]
 [5 4 0 3 2 1]]

Sorted array across columns/along rows:
[[26 42 43 68 91 99]
 [42 45 60 67 76 94]
 [14 32 38 41 42 43]
 [13 14 29 63 79 81]]



9. Create a 2D NumPy array with dimensions 3x3 filled with random integers between 1 and 100. Sort each row of the array in-place using the `sort()` method.


In [48]:
array = np.random.randint(1,100,size=(3,3))
print(f'Array:\n{array}\n')
array.sort(axis=1)
print(f'Sorted array along rows/across columns:\n{array}\n')


Array:
[[82 77 77]
 [90 39 63]
 [64  9 62]]

Sorted array along rows/across columns:
[[77 77 82]
 [39 63 90]
 [ 9 62 64]]




10. Create a 2D NumPy array with dimensions 5x2 filled with random integers between 1 and 100. Sort each column of the array in-place using the `sort()` method and the `axis` parameter.



In [50]:
a = np.random.randint(1,100,size=(5,2))
a.sort(axis=0)
print(f'Sorted random array across rows/along colums:\n{a}')

Sorted random array across rows/along colums:
[[34  2]
 [59  9]
 [81 16]
 [92 47]
 [97 97]]
