# 09 Exercises: Broadcasting
**Note**: If any exercises require techniques we haven't covered yet - you should look this up! It's part of the learning process, we need to build the muscle of learning how to do things we haven't seen before.

Don't be shy, ask for help on Discord!

For each exercise, print the shapes of the arrays involved and the result of the operation to check your understanding of broadcasting rules.


1. Create a 1D NumPy array with 5 elements and add a scalar value to it.


In [87]:
import numpy as np

a = np.arange(5)
print(f'Array: {a}')
a = a + 5
print(f'Array with +5 scalar value added: {a}')


Array: [0 1 2 3 4]
Array with +5 scalar value added: [5 6 7 8 9]



2. Create a 2D NumPy array with dimensions 3x4 and subtract a 1D array with 4 elements from each row of the 2D array.


In [88]:
a = np.arange(12).reshape(3,4)
print(f'Array a: \n{a}\n')
b = np.arange(4)
print(f"Array b: {b}\n")
c = a - b
print(f'Subtract a-b: \n{c}')

Array a: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array b: [0 1 2 3]

Subtract a-b: 
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]



3. Create a 2D NumPy array with dimensions 4x3 and multiply it by a 1D array with 3 elements.


In [89]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
c = a*b
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')
print(f'Array a*b:\n{c}')

Array a:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Array b:
[0 1 2]

Array a*b:
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]
 [ 0 10 22]]



4. Create a 3D NumPy array with dimensions 2x3x4 and add a 2D array with dimensions 3x4 to each 2D slice of the 3D array.


In [90]:
a = np.arange(24).reshape(2,3,4)
print(f'Array a:\n{a}\n')

b = np.arange(12).reshape(3,4)
print(f'Array b:\n{b}\n')

c = a + b
print(f'Result a+b:\n{c}')

Array a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Array b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Result a+b:
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]



5. Create a 2D NumPy array with dimensions 5x2 and divide it by a 2D array with dimensions 1x2.


In [91]:
a = np.arange(100,110).reshape(5,2)
b = np.arange(1,3).reshape(1,2)
c = a/b
print(c)

[[100.   50.5]
 [102.   51.5]
 [104.   52.5]
 [106.   53.5]
 [108.   54.5]]



6. Create a 2D NumPy array with dimensions 3x3 and add a 1D array with 3 elements to each column of the 2D array.


In [92]:
a = np.arange(9).reshape(3,3)
b = np.arange(3).reshape(3,1)
c = a+b
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')
print(f'Array a+b:\n{c}\n')

Array a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Array b:
[[0]
 [1]
 [2]]

Array a+b:
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]




7. Create a 3D NumPy array with dimensions 4x2x3 and multiply it by a 3D array with dimensions 1x2x3.


In [93]:
a = np.arange(24).reshape(4,2,-1)
b = np.arange(6).reshape(1,-1,3)
print(f'array a:\n{a}\n')
print(f'array b:\n{b}\n')
c = a * b
print(f'array a*b:\n{c}\n')


array a:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]

array b:
[[[0 1 2]
  [3 4 5]]]

array a*b:
[[[  0   1   4]
  [  9  16  25]]

 [[  0   7  16]
  [ 27  40  55]]

 [[  0  13  28]
  [ 45  64  85]]

 [[  0  19  40]
  [ 63  88 115]]]




8. Create a 2D NumPy array with dimensions 4x4 and subtract a scalar value from each element of the array.


In [94]:
a = np.arange(16).reshape(4,4)
c = a-3
print(f'Array:\n{a}\n')
print(f'Subtract array-3:\n{c}')

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Subtract array-3:
[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



9. Create a 3D NumPy array with dimensions 2x2x3 and divide it by a 2D array with dimensions 1x3.


In [95]:
a = np.arange(1,13).reshape(2,2,3)
b = np.arange(1,4).reshape(1,3)
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')

c = a/b
print(f'Array a/b:\n{c}')

Array a:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Array b:
[[1 2 3]]

Array a/b:
[[[ 1.   1.   1. ]
  [ 4.   2.5  2. ]]

 [[ 7.   4.   3. ]
  [10.   5.5  4. ]]]



10. Create a 2D NumPy array with dimensions 3x5 and add a 1D array with 1 element to each row of the 2D array.


In [96]:
a = np.arange(15).reshape(3,5)
b = np.array([9])
print(f"Array a:\n{a}\n")
print(f"Array b:\n{b}\n")

c = a+b
print(f'Array a+b:\n{c}')

Array a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Array b:
[9]

Array a+b:
[[ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]]



11. Create a 3D NumPy array with dimensions 2x4x3 and subtract a 2D array with dimensions 4x1 from each 3D slice of the 3D array.


In [97]:
a = np.arange(1,25).reshape(2,4,3)
b = np.arange(4).reshape(4,1)
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')

c=a-b
print(f'Array a-b:\n{c}')

Array a:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]

Array b:
[[0]
 [1]
 [2]
 [3]]

Array a-b:
[[[ 1  2  3]
  [ 3  4  5]
  [ 5  6  7]
  [ 7  8  9]]

 [[13 14 15]
  [15 16 17]
  [17 18 19]
  [19 20 21]]]



12. Create a 2D NumPy array with dimensions 4x2 and multiply it by a 2D array with dimensions 4x1.


In [98]:
a = np.arange(8).reshape(4,2)
b = np.arange(4).reshape(4,1)
c = a*b
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')
print(f'Array a*b:\n{c}')

Array a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Array b:
[[0]
 [1]
 [2]
 [3]]

Array a*b:
[[ 0  0]
 [ 2  3]
 [ 8 10]
 [18 21]]



13. Create a 3D NumPy array with dimensions 3x2x4 and add a 3D array with dimensions 3x1x1 to it.


In [99]:
a = np.arange(24).reshape(3,2,4)
b = np.arange(3).reshape(3,1,1)
print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')

c=a+b
print(f'Array a+b:\n{c}')


Array a:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Array b:
[[[0]]

 [[1]]

 [[2]]]

Array a+b:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[18 19 20 21]
  [22 23 24 25]]]



14. Create a 2D NumPy array with dimensions 5x3 and divide it by a 1D array with 1 element.


In [100]:
a = np.arange(15).reshape(5,3)
b = np.ones(1)*7
c = a/b

print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')
print(f'Array a/b:\n{c}')

Array a:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Array b:
[7.]

Array a/b:
[[0.         0.14285714 0.28571429]
 [0.42857143 0.57142857 0.71428571]
 [0.85714286 1.         1.14285714]
 [1.28571429 1.42857143 1.57142857]
 [1.71428571 1.85714286 2.        ]]



15. Create a 3D NumPy array with dimensions 2x3x4 and multiply it by a 3D array with dimensions 2x3x1.



In [102]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(6).reshape(2,3,1)
c = a*b

print(f'Array a:\n{a}\n')
print(f'Array b:\n{b}\n')
print(f'Array a*b:\n{c}')

Array a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Array b:
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

Array a*b:
[[[  0   0   0   0]
  [  4   5   6   7]
  [ 16  18  20  22]]

 [[ 36  39  42  45]
  [ 64  68  72  76]
  [100 105 110 115]]]
